package com.widiarifki.banyumusic;

import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author Widia Rifkianti
 */
public class LaguFrame extends javax.swing.JFrame {

    private Main mainFr;
    private Integer idLagu;

    /**
     * Creates new form LaguFrame
     */
    public LaguFrame(Main mainFr, Integer idRow) {
        this.idLagu = idRow;
        this.mainFr = mainFr;
        initComponents();
        setLocationRelativeTo(mainFr);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        /* jika user tidak login/belum register jangan tampilkan button 'tambah ke playlist' */
        if(this.mainFr.getIdUser() == 0){
            updatePlaylistBtn.setVisible(false);
        }else{
            updatePlaylistBtn.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RestTemplate client = new RestTemplate();
        String url = "http://widiarifki.com/banyumusic/lagu_json.php?id_lagu="+this.idLagu;
        Lagu hasil = client.getForObject(url, Lagu.class);
        labelGambar = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        judulText = new javax.swing.JLabel();
        artisText = new javax.swing.JLabel();
        genreText = new javax.swing.JLabel();
        labelArtis = new javax.swing.JLabel();
        labelGenre = new javax.swing.JLabel();
        updatePlaylistBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelGambar.setIcon(hasil.getPicture());
        labelGambar.setText("");

        labelJudul.setText(hasil.getTitle());

        judulText.setText("Judul");

        artisText.setText("Artis");

        genreText.setText("Genre");

        labelArtis.setText(hasil.getArtist());

        labelGenre.setText(hasil.getGenre());

        String btnText;

        String urlCheck = "http://widiarifki.com/banyumusic/playlist_check.php?id_lagu="+this.idLagu+"&id_user="+this.mainFr.getIdUser();
        Map<String, Boolean> hasilCheck = client.getForObject(urlCheck, HashMap.class);
        if(hasilCheck.get("is_exist")==true){
            btnText = "Hapus dari Playlist";
        }else{
            btnText = "Tambah ke Playlist";
        }
        updatePlaylistBtn.setText(btnText);
        updatePlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePlaylistBtnActionPerformed(evt);
            }
        });

        closeBtn.setText("Tutup");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulText)
                            .addComponent(artisText)
                            .addComponent(genreText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelJudul)
                            .addComponent(labelArtis)
                            .addComponent(labelGenre))
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updatePlaylistBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelJudul)
                            .addComponent(judulText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(artisText)
                            .addComponent(labelArtis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genreText)
                            .addComponent(labelGenre))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePlaylistBtn)
                    .addComponent(closeBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelGambar.getAccessibleContext().setAccessibleName("");
        labelJudul.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void updatePlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePlaylistBtnActionPerformed
        Playlist p = new Playlist();
        p.setId_lagu(this.idLagu);
        p.setId_user(this.mainFr.getIdUser());

        RestTemplate client = new RestTemplate();
        String url = "http://widiarifki.com/banyumusic/playlist_update.php";
        Map<String, Boolean> hasil = client.postForObject(url, p, HashMap.class);
        if(hasil.get("status")){
            final List<Lagu> laguData = new ArrayList<>();
            String urlPlaylist = "http://widiarifki.com/banyumusic/playlist_json.php?id_user="+this.mainFr.getIdUser();
            Playlist rows[] = client.getForObject(urlPlaylist, Playlist[].class);
            for (Playlist pl : rows) {
                laguData.add(pl.getData_lagu());
            }
            LaguModel laguMdl = new LaguModel(laguData){
                public String getColumnName(int column){
                    switch(column){
                        case 0: return "Judul";
                        case 1: return "Artis";
                        case 2: return "Genre";
                        default: return null;
                    }
                }
                public int getColumnCount(){
                    return 3;
                }
                public Object getValueAt(int row, int column){
                    Lagu l = laguData.get(row);
                    switch(column){
                        case 0: return l.getTitle();
                        case 1: return l.getArtist();
                        case 2: return l.getGenre();
                        default: return null;
                    }
                }
            };
            MyPlaylist myPlFrame = new MyPlaylist(this.mainFr, this.mainFr.getIdUser());
            myPlFrame.setVisible(false);
            myPlFrame.updatePlaylist(laguMdl);
            myPlFrame.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_updatePlaylistBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaguFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaguFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaguFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaguFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LaguFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artisText;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel genreText;
    private javax.swing.JLabel judulText;
    private javax.swing.JLabel labelArtis;
    private javax.swing.JLabel labelGambar;
    private javax.swing.JLabel labelGenre;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JButton updatePlaylistBtn;
    // End of variables declaration//GEN-END:variables
}
