package com.widiarifki.banyumusic;

import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.event.*;
import java.util.List;
import java.util.ArrayList;
import java.util.EventListener;
import java.awt.ItemSelectable;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseAdapter;
import org.springframework.web.client.RestTemplate;

public class MainFrame extends javax.swing.JFrame {

    private MainFrame mainFr = this;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        setTitle("Banyumusic");
        initComponents();
        this.jLabel1.setVisible(false);
        this.jButton3.setVisible(false);
    }

    public void aturBtn(String namaUser){
        this.jLabel1.setText("Hi "+namaUser+" !");
        this.jLabel1.setVisible(true);
        this.jButton3.setVisible(true);
        this.jButton1.setVisible(false);
        this.jButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RestTemplate client = new RestTemplate();

        /*HTTP Request*/
        final List<Lagu> laguData = new ArrayList<>();
        String url = "http://widiarifki.com/banyumusic/lagu_json.php";
        Lagu rows[] = client.getForObject(url, Lagu[].class);
        for (Lagu l : rows) {
            System.out.println(l.getTitle());
            laguData.add(l);
        }
        LaguModel laguMdl = new LaguModel(laguData);
        /*end - HTTP Request*/
        jTable1 = new javax.swing.JTable(laguMdl){
            public Class getColumnClass(int column)
            {
                return getValueAt(0, column).getClass();
            }
        };
        
        jTable1.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent event)
            {
              if (event.getClickCount() == 2) {

                System.out.println("double clicked");
                JTable table = (JTable) event.getSource();
                LaguModel model = (LaguModel)table.getModel();
                int row = table.convertRowIndexToModel(table.getSelectedRow());
                Lagu dataRow = model.getRowAt(row);

                LaguFrame laguFr = new LaguFrame(mainFr, dataRow.getId());
                laguFr.setTitle(dataRow.getTitle());
                laguFr.setVisible(true);

              }
            }
        });

        jPanel1 = new javax.swing.JPanel();
        /*HTTP Request*/
        String[] daftarGenre = new String[1];
        daftarGenre[0] = "Semua Genre";
        String urlG = "http://widiarifki.com/banyumusic/genre_json.php";
        Genre rowsG[] = client.getForObject(urlG, Genre[].class);
        for (Genre g : rowsG) {
            String[] daftarGenreOld = daftarGenre;
            Integer arrSize = daftarGenreOld.length+1;
            daftarGenre = new String[arrSize];
            System.arraycopy(daftarGenreOld, 0, daftarGenre, 0, daftarGenreOld.length);
            daftarGenre[daftarGenreOld.length] = g.getGenre();
        }
        /*end - HTTP Request*/
        jComboBox1 = new javax.swing.JComboBox(daftarGenre);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jScrollPane1.setViewportView(jTable1);
        jTable1.setRowHeight(150);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox1.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent itemEvent) {
                changeGenreAction(itemEvent);
            }
        });

        jButton1.setText("Daftar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("My Playlist");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.out.println("Register");
        RegFrame reg = new RegFrame(this);
        reg.setVisible(true);
        reg.setTitle("Daftar");
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void changeGenreAction(ItemEvent itemEvent) {
        int state = itemEvent.getStateChange();
        ItemSelectable is = itemEvent.getItemSelectable();
        String selected = selectedString(is);

        RestTemplate client = new RestTemplate();
        String url = "http://widiarifki.com/banyumusic/lagu_json.php?genre="+selected;
        
        List<Lagu> laguData = new ArrayList<>();
        Lagu rows[] = client.getForObject(url, Lagu[].class);
        for (Lagu l : rows) {
            System.out.println(l.getTitle());
            laguData.add(l);
        }
        LaguModel laguMdl = new LaguModel(laguData);
        jTable1.setModel(laguMdl);
    }

    static private String selectedString(ItemSelectable is) {
        Object selected[] = is.getSelectedObjects();
        return ((selected.length == 0) ? "null" : (String) selected[0]);
    }


    class TabelClickListener implements ListSelectionListener {
        private JTable tabel;
        private List<Lagu> data;

        public TabelClickListener(JTable t, List<Lagu> d){
            tabel = t;
            data = d;
        }

        public void valueChanged(ListSelectionEvent e){
            Object eventSource = e.getSource();
            System.out.println("Event source class : "+eventSource.getClass().getName());

            System.out.println("Baris yang diklik : "+tabel.getSelectedRow());
            
            Lagu m = data.get(tabel.getSelectedRow());

            System.out.println("NPM : "+m.getTitle());

            LaguFrame laguFr = new LaguFrame(mainFr, m.getId());
            laguFr.setVisible(true);
        }
    }

}
