/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.widiarifki.banyumusic;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author Widia Rifkianti
 */
public class MyPlaylist extends javax.swing.JFrame {
    
    private Integer idUser;
    private Main mainFr;
    /**
     * Creates new form MyPlaylist
     */
    public MyPlaylist(Main mainFr, Integer idUser) {
        this.mainFr = mainFr;
        this.idUser = idUser;
        initComponents();
        setLocationRelativeTo(mainFr);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        /*HTTP Request*/
        RestTemplate client = new RestTemplate();
        final List<Lagu> laguData = new ArrayList<>();
        String url = "http://widiarifki.com/banyumusic/playlist_json.php?id_user="+this.idUser;
        Playlist rows[] = client.getForObject(url, Playlist[].class);
        for (Playlist p : rows) {
            laguData.add(p.getData_lagu());
        }
        LaguModel laguMdl = new LaguModel(laguData){
            public String getColumnName(int column){
                switch(column){
                    case 0: return "Judul";
                    case 1: return "Artis";
                    case 2: return "Genre";
                    default: return null;
                }
            }
            public int getColumnCount(){
                return 3;
            }
            public Object getValueAt(int row, int column){
                Lagu l = laguData.get(row);
                switch(column){
                    case 0: return l.getTitle();
                    case 1: return l.getArtist();
                    case 2: return l.getGenre();
                    default: return null;
                }
            }
        };
        playlistTbl = new javax.swing.JTable();
        myPlaylistLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playlistTbl.setModel(laguMdl);
        jScrollPane1.setViewportView(playlistTbl);
        playlistTbl.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent event)
            {
                if (event.getClickCount() == 2) {

                    JTable table = (JTable) event.getSource();
                    LaguModel model = (LaguModel)table.getModel();
                    int row = table.convertRowIndexToModel(table.getSelectedRow());
                    Lagu dataRow = model.getRowAt(row);
                    LaguFrame laguFr = new LaguFrame(mainFr, dataRow.getId());
                    laguFr.setTitle(dataRow.getTitle());
                    laguFr.setVisible(true);

                }
            }
        });

        myPlaylistLabel.setText("My Playlist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myPlaylistLabel)
                        .addGap(0, 330, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myPlaylistLabel)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MyPlaylist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel myPlaylistLabel;
    private javax.swing.JTable playlistTbl;
    // End of variables declaration//GEN-END:variables
    
    void updatePlaylist(LaguModel laguMdl) {
        this.playlistTbl.setModel((TableModel) laguMdl);
    }
}
